---
language: ruby
os: linux
dist: xenial
cache: bundler
before_install: gem install bundler -v 2.1.2
script:
- bundle exec rake rubocop
- bundle exec rake rspec
jobs:
  fast_finish: true
  include:
  - rvm: 2.7.1
  - rvm: ruby-head
  - rvm: jruby-head
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
