---
language: ruby
cache: bundler
before_install: gem install bundler -v 2.1.2
script:
- bundle exec rake rubocop
- bundle exec rake rspec
jobs:
  fast_finish: true
  include:
  - rvm: 2.7.1
    os: [linux, osx]
  - rvm: ruby-head
    os: [linux, osx]
  - rvm: jruby-head
    os: [linux, osx]
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
